"""
historical_revert_to_prose.py
====================================
One-time revert: undoes historical_import.py's Q&A extraction and restores the
638 successfully-converted historical techsupport entries to their ORIGINAL
prose summary text (data/historical_import/summaries/*.txt, verbatim, no
paraphrasing/reprocessing), each prefixed with a short generated title as a
markdown heading -- e.g. "## Zookeeper GC Logging Configuration" -- matching
the title+summary format techsupport_qa_ingest.py now uses for all
techsupport content (see its module docstring). Only the title is
newly-generated by an LLM call (one per entry, techsupport_qa_ingest.generate_title);
the summary text itself is never touched.

Per user decision: the 2 pre-existing non-historical entries in
techsupport_qa_pairs.md (a hand-seeded LDAP entry, and a stray untracked test
entry) are dropped entirely, not converted -- the rewritten markdown file
contains ONLY the 638 historical entries.

Reconstructing the 638 entries and their order: historical_import_state.json
(already on disk, untouched by this script) records the outcome of every
parsed summary entry ("converted" / "skipped" / "error"), keyed by a stable
"<source_file>::<conversation_number>" id, but NOT in append order (it's
saved with sort_keys=True). The actual append order is fully determined by
re-parsing data/historical_import/summaries/*.txt the same way
historical_import.py's parse_all_summaries() does (files sorted by part
number, entries in file order) and filtering to ids with outcome=="converted"
-- historical_import.py always processes pending entries in that exact fixed
order, regardless of how many resumed runs it took, so this reproduces the
original append order exactly. (Deliberately does NOT import
historical_import.py itself to reuse its parser -- that module's own pipeline
is retired/out of sync with the new schema, see its module docstring -- the
~15 lines of parsing logic are duplicated here instead to keep this script
self-contained.)

Resumable: title-generation results are cached per entry id in
historical_revert_state.json (this directory) so re-running after a crash
doesn't regenerate titles that already succeeded. techsupport_qa_pairs.md
itself is NOT touched until every one of the 638 titles is ready -- the
rewrite is a single atomic step at the end, once, so a crash never leaves it
half-migrated.

Usage:
    # Dry run: generate/print titles only, touch nothing on disk.
    python historical_revert_to_prose.py --dry-run --limit 10

    # Real run: generate any remaining titles, then (once all 638 are ready)
    # rewrite techsupport_qa_pairs.md, reset techsupport_review_state.json,
    # and rebuild TECHSUPPORT_QA_PAIRS from the new markdown. Resumable --
    # safe to re-run if it stops partway through title generation.
    python historical_revert_to_prose.py

    # Real run without the final reembed (e.g. to split steps):
    python historical_revert_to_prose.py --skip-reembed
"""

import argparse
import html
import json
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from paths import LILLISA_SERVER_ROOT, PACKAGE_ROOT, ensure_import_paths

ensure_import_paths()
SCRIPT_DIR = PACKAGE_ROOT
PROJECT_ROOT = LILLISA_SERVER_ROOT
SUMMARIES_DIR = PROJECT_ROOT / "data" / "historical_import" / "summaries"
HISTORICAL_IMPORT_STATE_PATH = SCRIPT_DIR / "historical_import_state.json"
REVERT_STATE_PATH = SCRIPT_DIR / "historical_revert_state.json"
EXPECTED_CONVERTED_COUNT = 638

from techsupport_classifier import configure_dspy_lm  # noqa: E402
from techsupport_qa_ingest import (  # noqa: E402
    TECHSUPPORT_QA_MARKDOWN_FILENAME,
    VERIFIED_TECHSUPPORT_QA_FOLDERPATH,
    generate_title,
    save_review_state,
)
import techsupport_contextual_reembed  # noqa: E402


# --- Parsing: 36 files -> flat, ordered list of individual summary entries.
# Duplicated from historical_import.py (same regex/logic) rather than
# imported -- see module docstring. ---

_HEADER_PATTERN = re.compile(
    r"=== Conversation (\d+) Summary ===\n(.*?)(?=\n=== Conversation \d+ Summary ===|\Z)",
    re.DOTALL,
)
_PART_NUMBER_PATTERN = re.compile(r"(\d+)")


def _part_number(filename: str) -> int:
    """Natural sort key so summary_part_2.txt sorts before summary_part_10.txt."""
    match = _PART_NUMBER_PATTERN.search(filename)
    return int(match[1]) if match else 0


def parse_summary_file(path: Path) -> List[Dict[str, Any]]:
    text = path.read_text(encoding="utf-8")
    entries = []
    for match in _HEADER_PATTERN.finditer(text):
        conversation_number = int(match[1])
        summary_text = html.unescape(match[2].strip())
        if summary_text:
            entries.append({"conversation_number": conversation_number, "text": summary_text})
    return entries


def parse_all_summaries(summaries_dir: Path) -> List[Dict[str, Any]]:
    filenames = sorted((f.name for f in summaries_dir.glob("*.txt")), key=_part_number)
    all_entries = []
    for filename in filenames:
        for entry in parse_summary_file(summaries_dir / filename):
            entry["source_file"] = filename
            entry["id"] = f"{filename}::{entry['conversation_number']}"
            all_entries.append(entry)
    return all_entries


# --- Reconstruct the 638 converted historical entries, in original order ---


def get_converted_entries_in_order() -> List[Dict[str, Any]]:
    all_entries = parse_all_summaries(SUMMARIES_DIR)
    with open(HISTORICAL_IMPORT_STATE_PATH, encoding="utf-8") as f:
        import_state = json.load(f)

    converted_ids = {
        entry_id for entry_id, record in import_state["entries"].items()
        if record.get("outcome") == "converted"
    }
    return [entry for entry in all_entries if entry["id"] in converted_ids]


# --- State tracking for title generation (mirrors historical_import.py's pattern) ---


def load_revert_state() -> Dict[str, Any]:
    if not REVERT_STATE_PATH.exists():
        return {"titles": {}}
    with open(REVERT_STATE_PATH, encoding="utf-8") as f:
        return json.load(f)


def save_revert_state(state: Dict[str, Any]) -> None:
    with open(REVERT_STATE_PATH, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, sort_keys=True)


MAX_TITLE_RETRIES = 5
RETRY_BACKOFF_SECONDS = 15  # multiplied by attempt number -- rate limits need real wall-clock time to clear


def _generate_title_with_retry(summary: str) -> str:
    """generate_title() wrapped with backoff for transient provider rate
    limits (seen in practice against the Mistral endpoint) -- dspy's own
    internal retries aren't enough to ride out a sustained rate-limit window."""
    configure_dspy_lm()
    for attempt in range(1, MAX_TITLE_RETRIES + 1):
        try:
            return generate_title(summary=summary).title.strip()
        except Exception as exc:  # noqa: BLE001 -- retry on any transient provider error
            if attempt >= MAX_TITLE_RETRIES:
                raise
            wait_seconds = RETRY_BACKOFF_SECONDS * attempt
            print(f"(attempt {attempt} failed: {exc!r} -- retrying in {wait_seconds}s)", end=" ", flush=True)
            time.sleep(wait_seconds)
    raise RuntimeError("title generation failed after retries with no exception")


def generate_titles(entries: List[Dict[str, Any]], limit: Optional[int] = None, dry_run: bool = False) -> tuple:
    """Generate (and cache) a short title for each entry's ORIGINAL summary
    text -- the summary text itself is never modified. Returns
    (titles_by_id, count_generated_this_run)."""
    revert_state = load_revert_state()
    titles = revert_state["titles"]

    pending = [e for e in entries if e["id"] not in titles]
    if limit is not None:
        pending = pending[:limit]

    for i, entry in enumerate(pending, 1):
        print(f"[{i}/{len(pending)}] {entry['id']} ...", end=" ", flush=True)
        title = _generate_title_with_retry(entry["text"])
        print(title)
        titles[entry["id"]] = title
        if not dry_run:
            save_revert_state(revert_state)

    return titles, len(pending)


def rewrite_markdown(entries: List[Dict[str, Any]], titles: Dict[str, str]) -> Path:
    """Single atomic rewrite of techsupport_qa_pairs.md: ONLY the 638
    historical entries, each as '## {title}\\n\\n{original_summary_text}\\n\\n'
    -- the 2 pre-existing non-historical entries are dropped entirely (user
    decision, see module docstring)."""
    VERIFIED_TECHSUPPORT_QA_FOLDERPATH.mkdir(parents=True, exist_ok=True)
    filepath = VERIFIED_TECHSUPPORT_QA_FOLDERPATH / TECHSUPPORT_QA_MARKDOWN_FILENAME
    content = "".join(
        f"## {titles[entry['id']]}\n\n{entry['text']}\n\n"
        for entry in entries
    )
    filepath.write_text(content, encoding="utf-8")
    return filepath


def run(limit: Optional[int] = None, dry_run: bool = False, skip_reembed: bool = False) -> Dict[str, Any]:
    entries = get_converted_entries_in_order()
    if len(entries) != EXPECTED_CONVERTED_COUNT:
        raise RuntimeError(
            f"Expected exactly {EXPECTED_CONVERTED_COUNT} converted historical entries, found "
            f"{len(entries)} -- refusing to proceed (historical_import_state.json or the summaries "
            "under data/historical_import/summaries/ may have changed since this script was written)."
        )

    titles, generated_this_run = generate_titles(entries, limit=limit, dry_run=dry_run)

    if dry_run:
        return {
            "dry_run": True,
            "total_entries": len(entries),
            "titles_generated_this_run": generated_this_run,
            "titles_cached_total": len(titles),
        }

    missing = [e["id"] for e in entries if e["id"] not in titles]
    if missing:
        return {
            "dry_run": False,
            "complete": False,
            "total_entries": len(entries),
            "titles_ready": len(titles),
            "missing_titles": len(missing),
            "message": "Not all titles generated yet -- run again (optionally without --limit) to finish before rewriting markdown.",
        }

    markdown_path = rewrite_markdown(entries, titles)

    # All markdown positions are being renumbered by this rewrite, and none of
    # the 638 historical entries were ever tracked in review_state anyway
    # (see techsupport_qa_ingest.py's module docstring).
    save_review_state({"entries": {}})

    reembed_result = None
    if not skip_reembed:
        print("\nTriggering full contextual re-embed of TECHSUPPORT_QA_PAIRS ...")
        reembed_result = techsupport_contextual_reembed.run_reembed()
        reembed_state = techsupport_contextual_reembed.load_state()
        reembed_state["last_reembed_timestamp"] = f"{time.time():.6f}"
        techsupport_contextual_reembed.save_state(reembed_state)
        print(f"Reembed done: {reembed_result}")

    return {
        "dry_run": False,
        "complete": True,
        "total_entries": len(entries),
        "markdown_path": str(markdown_path),
        "review_state_reset": True,
        "reembed_result": reembed_result,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--limit", type=int, default=None, help="Max number of not-yet-titled entries to process this run")
    parser.add_argument("--dry-run", action="store_true", help="Generate/print titles only; write nothing to disk")
    parser.add_argument("--skip-reembed", action="store_true", help="Skip the final full contextual re-embed step")
    args = parser.parse_args()

    result = run(limit=args.limit, dry_run=args.dry_run, skip_reembed=args.skip_reembed)
    print("\n=== Historical Revert Summary ===")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
